// created pipeline for creating AWS bastion host
// agetnt, environment
// options => timeout and ansiColor
// stages => inti, plan, apply, Destroy(not mandatory)
// create downstream for security group => trigger SG
// propagate, wait in downstream

pipeline{
    agent{
        label "AGENT-1"
    }

    environment{
        REGION = "us-east-1"
        ACC_ID = "741005748171"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }

    options{
        timeout(time: 30, unit: 'MINUTES') 
        ansiColor('xterm')
        disableConcurrentBuilds()
    }

    // parameters{

    // }

    stages {

        // init terraform using aws creds
        stage('init'){
            steps{
                script{
                    withAWS(credentials: 'aws-auth', region: 'us-east-1'){
                         sh """
                            cd 60-acm
                            terraform init -reconfigure
                        """
                    }

                }
            }
        }

        // terraform plan
        stage('plan'){
            steps{
                script{
                    withAWS(credentials: 'aws-auth', region: 'us-east-1'){
                         sh """
                            cd 60-acm
                            terraform plan
                        """
                    }

                }
            }
        }

        // terraform apply
        stage('apply'){
            // input {
            //     message "Should we continue?"
            //     ok "Yes, we should."
            //     submitter "alice,anil"
            // } 

            steps{
                script{
                    withAWS(credentials: 'aws-auth', region: 'us-east-1'){
                         sh """
                            cd 60-acm
                            terraform apply -auto-approve
                        """
                    }

                }
            }
        }
    }
}