pipeline{
    agent{
        label "AGENT-1"
    }

    environment{
        REGION = "us-east-1"
        ACC_ID = "741005748171"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }

    options{
        timeout(time: 30, unit: 'MINUTES') 
        ansiColor('xterm')
    }

    // parameters{

    // }

    stages {

        // init terraform using aws creds
        stage('init'){
            steps{
                script{
                    withAWS(credentials: 'aws-auth', region: 'us-east-1'){
                         sh """
                            cd 00-vpc
                            terraform init -reconfigure
                        """
                    }

                }
            }
        }
    }
}